#!/usr/bin/env python3
from pathlib import Path

p = Path('scripts/combat.gd')
s = p.read_text(encoding='utf-8')

s = s.replace('const CARD_GAP := -58.0\nconst CARD_Y := 735.0', 'const CARD_GAP := -78.0\nconst CARD_Y := 748.0\nconst CARD_FAN_ROTATION := 6.0\nconst CARD_FAN_LIFT := 17.0')
s = s.replace('const HP_DEF_FRAME_TEXTURE := preload("res://assets/ui/combat/hp_def_frame.png")', 'const HP_DEF_FRAME_TEXTURE := preload("res://assets/ui/combat/hp_def_frame_approved.png")')
s = s.replace('var drag_origin := Vector2.ZERO\nvar discard_window_open := true', 'var drag_origin := Vector2.ZERO\nvar drag_origin_rotation := 0.0\nvar drag_touch_position := Vector2.ZERO\nvar discard_window_open := true')
s = s.replace('var player_block_label: Label\nvar player_status_label: Label', 'var player_block_label: Label\nvar player_hp_fill: ColorRect\nvar player_block_fill: ColorRect\nvar player_status_label: Label')

old_ui = '''\tvar player_frame := TextureRect.new()\n\tplayer_frame.texture = HP_DEF_FRAME_TEXTURE\n\tplayer_frame.position = Vector2(34, 150)\n\tplayer_frame.size = Vector2(430, 242)\n\tplayer_frame.expand_mode = TextureRect.EXPAND_IGNORE_SIZE\n\tplayer_frame.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED\n\tplayer_frame.mouse_filter = Control.MOUSE_FILTER_IGNORE\n\tinterface.add_child(player_frame)\n\n\tplayer_hp_label = _make_label(\n\t\tVector2(155, 244), Vector2(265, 34), 20, Color(1.0, 0.9, 0.79)\n\t)\n\tplayer_hp_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER\n\tinterface.add_child(player_hp_label)\n\tplayer_block_label = _make_label(\n\t\tVector2(155, 286), Vector2(265, 34), 19, Color(0.72, 0.88, 1.0)\n\t)\n\tplayer_block_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER\n\tinterface.add_child(player_block_label)\n\tplayer_status_label = _make_label(\n\t\tVector2(48, 392), Vector2(430, 42), 13, Color(0.96, 0.82, 0.56)\n\t)\n\tinterface.add_child(player_status_label)'''
new_ui = '''\tplayer_hp_fill = ColorRect.new()\n\tplayer_hp_fill.position = Vector2(156, 124)\n\tplayer_hp_fill.size = Vector2(247, 18)\n\tplayer_hp_fill.color = Color(0.62, 0.02, 0.03, 0.95)\n\tplayer_hp_fill.mouse_filter = Control.MOUSE_FILTER_IGNORE\n\tinterface.add_child(player_hp_fill)\n\n\tplayer_block_fill = ColorRect.new()\n\tplayer_block_fill.position = Vector2(156, 162)\n\tplayer_block_fill.size = Vector2(0, 18)\n\tplayer_block_fill.color = Color(0.06, 0.22, 0.42, 0.95)\n\tplayer_block_fill.mouse_filter = Control.MOUSE_FILTER_IGNORE\n\tinterface.add_child(player_block_fill)\n\n\tvar player_frame := TextureRect.new()\n\tplayer_frame.texture = HP_DEF_FRAME_TEXTURE\n\tplayer_frame.position = Vector2(20, 96)\n\tplayer_frame.size = Vector2(420, 113)\n\tplayer_frame.expand_mode = TextureRect.EXPAND_IGNORE_SIZE\n\tplayer_frame.stretch_mode = TextureRect.STRETCH_SCALE\n\tplayer_frame.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST\n\tplayer_frame.mouse_filter = Control.MOUSE_FILTER_IGNORE\n\tinterface.add_child(player_frame)\n\n\tplayer_hp_label = _make_label(Vector2(156, 124), Vector2(247, 18), 12, Color(1.0, 0.92, 0.82))\n\tplayer_hp_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER\n\tplayer_hp_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER\n\tinterface.add_child(player_hp_label)\n\tplayer_block_label = _make_label(Vector2(156, 162), Vector2(247, 18), 11, Color(0.78, 0.9, 1.0))\n\tplayer_block_label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER\n\tplayer_block_label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER\n\tinterface.add_child(player_block_label)\n\tplayer_status_label = _make_label(Vector2(28, 216), Vector2(410, 26), 11, Color(0.96, 0.82, 0.56))\n\tinterface.add_child(player_status_label)'''
if old_ui not in s:
    raise SystemExit('UI block not found')
s = s.replace(old_ui, new_ui)

s = s.replace('''\t\t"PRIMER TURNO · CLIC DERECHO PARA DESCARTAR · ARRASTRA PARA JUGAR"\n\t\tif first_turn\n\t\telse "NUEVO TURNO · CLIC DERECHO PARA DESCARTAR · ARRASTRA PARA JUGAR"''', '''\t\t"PRIMER TURNO · ARRASTRA UNA CARTA PARA JUGAR"\n\t\tif first_turn\n\t\telse "NUEVO TURNO · ARRASTRA UNA CARTA PARA JUGAR"''')

start = s.index('func _rebuild_hand() -> void:')
end = s.index('func _finish_card_drag() -> void:')
new_hand = '''func _rebuild_hand() -> void:\n\tfor button in card_buttons:\n\t\tif is_instance_valid(button):\n\t\t\tbutton.queue_free()\n\tcard_buttons.clear()\n\n\tvar count := deck.hand.size()\n\tif count == 0:\n\t\treturn\n\tvar step := CARD_SIZE.x + CARD_GAP\n\tvar center := (count - 1) / 2.0\n\tvar start_x := 960.0 - CARD_SIZE.x / 2.0 - center * step\n\tfor card_index in count:\n\t\tvar card_id: StringName = deck.hand[card_index]\n\t\tvar offset := card_index - center\n\t\tvar button := TextureButton.new()\n\t\tbutton.texture_normal = CARD_TEXTURES[card_id]\n\t\tbutton.ignore_texture_size = true\n\t\tbutton.stretch_mode = TextureButton.STRETCH_KEEP_ASPECT_CENTERED\n\t\tbutton.clip_contents = false\n\t\tbutton.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST\n\t\tbutton.size = CARD_SIZE\n\t\tbutton.pivot_offset = CARD_SIZE / 2.0\n\t\tbutton.position = Vector2(start_x + card_index * step, CARD_Y + absf(offset) * CARD_FAN_LIFT)\n\t\tbutton.rotation = deg_to_rad(offset * CARD_FAN_ROTATION)\n\t\tbutton.z_index = card_index\n\t\tbutton.set_meta("card_id", card_id)\n\t\tbutton.gui_input.connect(_on_card_input.bind(button))\n\t\tinterface.add_child(button)\n\t\tcard_buttons.append(button)\n\n\nfunc _start_card_drag(button: TextureButton, card_id: StringName, pointer: Vector2) -> void:\n\tdrag_card = button\n\tdrag_card_id = card_id\n\tdrag_origin = button.position\n\tdrag_origin_rotation = button.rotation\n\tdrag_touch_position = pointer\n\tbutton.rotation = 0.0\n\tbutton.z_index = 100\n\tbutton.modulate = Color(1.08, 1.08, 1.08)\n\n\nfunc _move_card_drag(pointer: Vector2) -> void:\n\tif not is_instance_valid(drag_card):\n\t\treturn\n\tvar delta := pointer - drag_touch_position\n\tdrag_card.position += delta\n\tdrag_touch_position = pointer\n\t_refresh_enemy_highlight(pointer)\n\n\nfunc _on_card_input(event: InputEvent, button: TextureButton) -> void:\n\tif combat_finished:\n\t\treturn\n\tvar card_id: StringName = button.get_meta("card_id")\n\tif event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:\n\t\tif event.pressed:\n\t\t\t_start_card_drag(button, card_id, get_viewport().get_mouse_position())\n\t\telif drag_card == button:\n\t\t\t_finish_card_drag()\n\t\tbutton.accept_event()\n\telif event is InputEventMouseMotion and drag_card == button:\n\t\t_move_card_drag(get_viewport().get_mouse_position())\n\t\tbutton.accept_event()\n\telif event is InputEventScreenTouch:\n\t\tif event.pressed:\n\t\t\t_start_card_drag(button, card_id, event.position)\n\t\telif drag_card == button:\n\t\t\t_finish_card_drag()\n\t\tbutton.accept_event()\n\telif event is InputEventScreenDrag and drag_card == button:\n\t\t_move_card_drag(event.position)\n\t\tbutton.accept_event()\n\n\n'''
s = s[:start] + new_hand + s[end:]
s = s.replace('\tdrag_card.position = drag_origin\n\tdrag_card.z_index = 0\n\tdrag_card.modulate = Color.WHITE', '\tdrag_card.position = drag_origin\n\tdrag_card.rotation = drag_origin_rotation\n\tdrag_card.z_index = card_buttons.find(drag_card)\n\tdrag_card.modulate = Color.WHITE')
s = s.replace('player_block_label.text = "DEF  %d" % player.block\n\tplayer_status_label.text', 'player_block_label.text = "DEF  %d" % player.block\n\tplayer_hp_fill.size.x = 247.0 * clampf(float(player.hp) / float(player.max_hp), 0.0, 1.0)\n\tplayer_block_fill.size.x = 247.0 * clampf(float(player.block) / 20.0, 0.0, 1.0)\n\tplayer_status_label.text')
p.write_text(s, encoding='utf-8')
print('combat fixed')
